services:
  db:
    image: postgres:16-alpine
    container_name: green-elegance-db
    environment:
      POSTGRES_DB: greenelegance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
