ALTER TABLE orders ALTER COLUMN subtotal TYPE DECIMAL(38, 2);
ALTER TABLE orders ALTER COLUMN shipping_fee TYPE DECIMAL(38, 2);
ALTER TABLE orders ALTER COLUMN grand_total TYPE DECIMAL(38, 2);
ALTER TABLE order_items ALTER COLUMN price TYPE DECIMAL(38, 2);
